apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
    - name: hamzabaker/docker-vote-app
      newTag: 65f1ab92637cc9a4dc15be32666d1348d0096e27

    - name: hamzabaker/docker-result-app
      newTag: 65f1ab92637cc9a4dc15be32666d1348d0096e27

    - name: hamzabaker/docker-worker
      newTag: 65f1ab92637cc9a4dc15be32666d1348d0096e27


resources:
  - namespace.yaml

  - configmap/app-config.yaml

  - secret/postgres-secret.yaml

  - redis/deployment.yaml

  - redis/service.yaml

  - postgres/pv.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/deployment.yaml

  - vote-app/service.yaml
  - vote-app/deployment.yaml

  - result-app/service.yaml
  - result-app/deployment.yaml

  - worker/deployment.yaml

  - ingress/ingress.yaml
