apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: feedback-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # postgres
  POSTGRES_PASSWORD: cG9zdG1l        # postgres
  POSTGRES_DB: ZmVlZGJhY2tkYg==     # feedbackdb
